name: Build and Deploy Hexo Site

on:
  push:
    branches:
      - main  # 替换为你的默认分支名称，如果不同的话

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'  # 使用 Node.js v20 LTS 版本

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install additional plugins (if needed)
        run: |
          # 下面的插件安装可以根据需要启用
          npm install hexo-cli -g
          # npm install hexo-renderer-markdown-it-plus --save
          # npm install hexo-math --save
          # npm install hexo-generator-feed --save
          # npm install hexo-next-giscus --save
      
      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # 确保只在默认分支上部署
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: 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
          publish_dir: ./nicemxm.github.io/public
          
      - name: Deploy NICEMXM's Blog # 设置 git 信息并推送静态博客文件
        run: |
          git config --global user.name "NICEMXM"
          git config --global user.email "1204192242@qq.com"
          hexo deploy

      - run: echo "Deploy Successful!"
  
